### ISSUE TITLE
Kinda confusing

### ISSUE THREAD

**Issue by SurvoltX** [nexuspcs/Kahoot-Spammer#1]
I had run the project on replit, however it does not show anything? I did wait for the console to say "press enter twice", nothing. Can I have help with this?

**Comment by nexuspcs** [comment]
if you have a powerful pc (about 16gb  ram (or more)), try running it via CMD/terminal on your local machine

**Comment by nexuspcs** [comment]
Let me know how it goes with running it from your local machine

**Comment by AndyIsHereBoi** [comment]
replit has 200-400mb of ram u shouldnt say it will run on replit then

**Comment by nexuspcs** [comment]
> replit has 200-400mb of ram u shouldnt say it will run on replit then

Well it's a free to use repo don't get mad if it doesn't work since it was free and open source.

**Comment by nexuspcs** [comment]
> replit has 200-400mb of ram u shouldnt say it will run on replit then

Well it's a free to use repo don't get mad if it doesn't work since it was free and open source.

**Comment by AndyIsHereBoi** [comment]
I was just saying that replit can not run it so I was suggesting you don't
put it there as a way to run it
