### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by nexuspcs** [nexuspcs/Kahoot-Spammer#2]
### **Please note**

To run this, your computer needs to have about 16gb of RAM, or higher, since using this script will flood the connections with bots, (duplicates), which can be quite resource heavy

> Click this video to see how much RAM you have [Windows](https://www.youtube.com/watch?v=9sIA1vMlGuQ) || [MacOS](https://www.youtube.com/watch?v=igJ-k_xnP0U)

**Comment by Jeydin21** [comment]
whyd you copy me dude
